name: Build and Deploy Website

on:
  push:
    branches:
      - master
    paths:
      - 'Backend/**'
      - 'Frontend/**'
      - 'Dockerfile'
      - '.gitea/workflows/build-and-deploy.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.smpark.in
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.smpark.in/smparkin/website:latest
          cache-from: type=registry,ref=registry.smpark.in/smparkin/website:buildcache
          cache-to: type=registry,ref=registry.smpark.in/smparkin/website:buildcache,mode=max

      - name: Summary
        run: |
          echo "Built and pushed registry.smpark.in/smparkin/website:latest"
